[project]
name = "torchgeometric"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "neo4j>=5.28.1",
    "torch-geometric>=2.6.1",
    "torch==2.5.0",
    "typing-extensions>=4.13.0",
    "sympy>=1.13.1",
    "scipy>=1.15.2",
]


[project.optional-dependencies]
cpu = [
    "torch>=2.5.0",
    "torch-sparse==0.6.18+pt25cpu",
    "torch-scatter==2.1.2+pt25cpu",
]
cu124 = [
    "torch>=2.5.0",
    "torch-sparse==0.6.18+pt25cu124",
    "torch-scatter==2.1.2+pt25cu124",

]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu124" },
  ],
]
no-build-isolation-package = ['torch-sparse',"torch-scatter"]
find-links = [
  "https://data.pyg.org/whl/torch-2.5.0+cu124.html",
  "https://data.pyg.org/whl/torch-2.5.0+cpu.html",
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu", marker = "sys_platform == 'win32' or sys_platform == 'linux'" },
  { index = "pytorch-cu124", extra="cu124",marker = "sys_platform == 'win32' or sys_platform == 'linux'"},
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
